# This files contains everything needed to run this stack in development, staging, or production

version: '3.3'

services:
  db:
    image: paulrichter/camelot_db:1.0
    restart: unless-stopped
    ports:
      - 5435:5432
    networks:
      - glory_wall
    volumes:
      - glory_wall_db:/camelotDB
    environment:
      POSTGRES_USER: camelot
      POSTGRES_PASSWORD: camelot
      PGDATA: /camelotDB
      POSTGRES_DB: camelot
  glory_wall:
    image: paulrichter/camelot_glory_wall:1.0
    restart: unless-stopped
    networks:
      - glory_wall
    environment:
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_USERNAME=${SLACK_USERNAME}
      - UTOPIA_AGE=78
      - APP_ENV=DEBUG
    stdin_open: true
    tty: true
    command: "python glory_wall.py"

volumes:
  glory_wall_db:

networks:
  glory_wall:
    attachable: true
